[package]
name = "deskv"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "7.1.3"
num-derive = "0.4.2"
num-traits = "0.2.19"
thiserror = "2.0.3"

[dev-dependencies]
goblin = "0.10"
anyhow = "1.0"
